### ISSUE TITLE
[BUG反馈] 使用/zaphkiel reload或rebuild 重载物品时，材质icon的修改不会被全局更新同步

### ISSUE THREAD

**Issue by luoxiawuchen** [TabooLib/zaphkiel#39]
经测试，zap物品reload时，物品涉及材质icon、meta元数据native修改的部分不会被全局更新。
lore，name等数据有效。

**Comment by Bkm016** [comment]
怎么写的？

**Comment by Bkm016** [comment]
全靠一张嘴，让我猜呗

**Comment by luoxiawuchen** [comment]
> 怎么写的？

服务端测试环境：spigot-1.20.1

使用默认配置进行测试，修改icon项，/zap reload后背包内物品材质仍然为木剑。（使用/zap rebuild结果相同）
重新使用/zap give指令，可获得最新材质的物品
![image](https://github.com/TabooLib/zaphkiel/assets/64759847/111c450a-55a2-4d12-b84d-e3427e2c6d43)

视频演示：
https://github.com/TabooLib/zaphkiel/assets/64759847/a34bfabb-457e-4496-afc8-54c0bc1deb63

zap物品配置详情：
```
example_sword_1:
  display: default_display_1
  #icon: wooden_sword
  icon: apple
  name:
    item_name: '&7Wooden Sword 1'
  lore:
    item_type: '&9Sword'
    item_description:
      - '&fCan be bought everywhere.'
  data:
    durability: 10
  meta:
    durability:
      remains: minecraft:stick
    attribute:
      mainhand:
        damage: +7
        attack_speed: +10%
  event:
    on_damage: item damage 1
```

完整后台日志（未发现明显报错）：
[latest.log](https://github.com/TabooLib/zaphkiel/files/13861174/latest.log)

感谢坏佬耐心阅读
